const QUESTION_BANK = {
    math: [
        { id: "m1", q: "What is the general term of a binomial expansion?", a: ["T_r", "T_{r+1}", "T_{n}", "T_{r-1}"], c: 1 },
        { id: "m2", q: "If A is a symmetric matrix, then A^T is equal to:", a: ["-A", "A", "I", "0"], c: 1 },
        { id: "m3", q: "The multiplicative inverse of the complex number (a, b) is:", a: ["(a/(a²+b²), -b/(a²+b²))", "(-a/(a²+b²), b/(a²+b²))", "(a, -b)", "(-a, -b)"], c: 0 },
        { id: "m4", q: "If a matrix A has order 3x4, then the order of A^T is:", a: ["3x4", "4x3", "3x3", "4x4"], c: 1 },
        { id: "m5", q: "The determinant of a singular matrix is always:", a: ["1", "-1", "0", "Any real number"], c: 2 },
        { id: "m6", q: "The number of terms in the expansion of (x + y)^n is:", a: ["n", "n-1", "n+1", "2n"], c: 2 },
        { id: "m7", q: "If sin(x) = 1/2, then the principal value of x is:", a: ["π/3", "π/6", "π/4", "π/2"], c: 1 },
        { id: "m8", q: "The period of the trigonometric function tan(x) is:", a: ["π", "2π", "π/2", "3π"], c: 0 },
        { id: "m9", q: "The sum of the infinite geometric series 1 + 1/2 + 1/4 + 1/8 + ... is:", a: ["1.5", "2", "3", "Infinite"], c: 1 },
        { id: "m10", q: "The number of permutations of n different objects taken all at a time is:", a: ["n!", "(n-1)!", "n!/2", "n^n"], c: 0 },
        { id: "m11", q: "The slope of a line parallel to the x-axis is always:", a: ["1", "-1", "Undefined", "0"], c: 3 },
        { id: "m12", q: "The derivative of cos(x) with respect to x is:", a: ["sin(x)", "-sin(x)", "sec²(x)", "-cos(x)"], c: 1 },
        { id: "m13", q: "The integral of 1/x with respect to x is:", a: ["ln|x| + c", "x + c", "-1/x² + c", "e^x + c"], c: 0 },
        { id: "m14", q: "The distance of the point (3, 4) from the origin is:", a: ["5", "7", "25", "1"], c: 0 },
        { id: "m15", q: "If cos(x) = 0, then x is equal to:", a: ["0", "π", "π/2", "2π"], c: 2 },
        { id: "m16", q: "The solution set of the equation x² + 1 = 0 in complex numbers is:", a: ["{1, -1}", "{i, -i}", "{0}", "Empty set"], c: 1 },
        { id: "m17", q: "The arithmetic mean between a and b is given by:", a: ["√(ab)", "2ab/(a+b)", "(a+b)/2", "a-b"], c: 2 },
        { id: "m18", q: "The geometric mean between 4 and 9 is:", a: ["6.5", "6", "13", "36"], c: 1 },
        { id: "m19", q: "The focus of the parabola y² = 4ax is located at:", a: ["(0, a)", "(a, 0)", "(-a, 0)", "(0, -a)"], c: 1 },
        { id: "m20", q: "The eccentricity of a circle is always:", a: ["1", "Greater than 1", "Less than 1", "0"], c: 3 }
    ],
    physics: [
        { id: "p1", q: "The efficiency of a Carnot engine depends upon:", a: ["Sink temperature", "Source temperature", "Both source and sink temperatures", "Working substance"], c: 2 },
        { id: "p2", q: "Which lens is used to correct hyperopia?", a: ["Concave", "Convex", "Cylindrical", "Bifocal"], c: 1 },
        { id: "p3", q: "The dimensional formula for work or energy is:", a: ["[MLT⁻¹]", "[ML²T⁻²]", "[MLT⁻²]", "[ML²T⁻¹]"], c: 1 },
        { id: "p4", q: "The area under a velocity-time graph represents:", a: ["Acceleration", "Distance/Displacement", "Force", "Momentum"], c: 1 },
        { id: "p5", q: "A missile fired at an angle of 45° achieves maximum:", a: ["Height", "Horizontal Range", "Time of flight", "Velocity"], c: 1 },
        { id: "p6", q: "The value of escape velocity from the Earth's surface is approximately:", a: ["11.2 km/s", "9.8 km/s", "7.9 km/s", "11.2 m/s"], c: 0 },
        { id: "p7", q: "In an isolated system, the total linear momentum remains:", a: ["Zero", "Constant", "Variable", "Doubled"], c: 1 },
        { id: "p8", q: "The working of a dynamic lift of an airplane is based on:", a: ["Torricelli's theorem", "Stokes' law", "Bernoulli's principle", "Archimedes' principle"], c: 2 },
        { id: "p9", q: "The speed of sound is maximum in which of the following media?", a: ["Air", "Water", "Steel", "Vacuum"], c: 2 },
        { id: "p10", q: "When a wave enters a different medium, which property does NOT change?", a: ["Velocity", "Wavelength", "Frequency", "Amplitude"], c: 2 },
        { id: "p11", q: "The blue color of the sky is due to which optical phenomenon?", a: ["Refraction", "Interference", "Diffraction", "Scattering"], c: 3 },
        { id: "p12", q: "According to the Kinetic Theory of Gases, absolute zero is the temperature at which:", a: ["Water freezes", "Liquid helium boils", "Molecular motion stops", "Gases turn to ice"], c: 2 },
        { id: "p13", q: "The first law of thermodynamics is a restatement of the principle of conservation of:", a: ["Mass", "Energy", "Momentum", "Charge"], c: 1 },
        { id: "p14", q: "The SI unit of electric flux is:", a: ["N m² C⁻¹", "N C⁻¹", "Weber", "Tesla"], c: 0 },
        { id: "p15", q: "The resistance of an ideal voltmeter should ideally be:", a: ["Zero", "Very low", "Infinite", "100 Ohms"], c: 2 },
        { id: "p16", q: "The core of a transformer is laminated to reduce losses due to:", a: ["Hysteresis", "Eddy currents", "Copper heating", "Flux leakage"], c: 1 },
        { id: "p17", q: "Light waves are transverse in nature, which is explicitly proven by:", a: ["Interference", "Diffraction", "Polarization", "Reflection"], c: 2 },
        { id: "p18", q: "The energy stored in an inductor is in the form of:", a: ["Electric field", "Magnetic field", "Chemical energy", "Gravitational field"], c: 1 },
        { id: "p19", q: "The charge on an electron was experimentally determined by:", a: ["J.J. Thomson", "Rutherford", "Millikan", "Ampere"], c: 2 },
        { id: "p20", q: "Which type of radiation has the highest penetrating power?", a: ["Alpha rays", "Beta rays", "Gamma rays", "X-rays"], c: 2 }
    ],
    english: [
        { id: "e1", q: "Choose the synonym of 'ANOMALOUS':", a: ["Normal", "Abnormal", "Aggressive", "Capacious"], c: 1 },
        { id: "e2", q: "Identify the antonym of the word 'EXTOL':", a: ["Praise", "Criticize", "Magnify", "Exalt"], c: 1 },
        { id: "e3", q: "He is senior _______ me in age.", a: ["than", "to", "from", "with"], c: 1 },
        { id: "e4", q: "Choose the correct spelling:", a: ["Accommodation", "Acomodation", "Accomodation", "Acommodation"], c: 0 },
        { id: "e5", q: "She has been living here ________ 2018.", a: ["for", "since", "from", "by"], c: 1 },
        { id: "e6", q: "Complete the conditional: 'If I had studied harder, I _______ the test.'", a: ["would pass", "will pass", "would have passed", "had passed"], c: 2 },
        { id: "e7", q: "Choose the synonym of 'EPHEMERAL':", a: ["Eternal", "Short-lived", "Beautiful", "Monotonous"], c: 1 },
        { id: "e8", q: "The idiom 'To turn over a new leaf' means:", a: ["To plant a tree", "To change behavior for the better", "To read a new book", "To travel somewhere new"], c: 1 },
        { id: "e9", q: "Neither the teacher nor the students _______ present today.", a: ["is", "are", "was", "has been"], c: 1 },
        { id: "e10", q: "Identify the part of speech of the underlined word: 'The *fast* train arrived late.'", a: ["Noun", "Adverb", "Adjective", "Verb"], c: 2 },
        { id: "e11", q: "Choose the antonym of 'COMPASSIONATE':", a: ["Kind", "Cruel", "Sympathetic", "Merciful"], c: 1 },
        { id: "e12", q: "The child died _______ cholera.", a: ["from", "with", "by", "of"], c: 3 },
        { id: "e13", q: "Choose the correct passive voice of: 'She sings a song.'", a: ["A song was sung by her.", "A song is sung by her.", "A song is being sung by her.", "A song has been sung by her."], c: 1 },
        { id: "e14", q: "A person who hates mankind is called a:", a: ["Philanthropist", "Misanthrope", "Optimist", "Pessimist"], c: 1 },
        { id: "e15", q: "Select the sentence with correct punctuation:", a: ["Wow that is a beautiful car.", "Wow, that is a beautiful car!", "Wow! that is a beautiful car?", "Wow; that is a beautiful car."], c: 1 },
        { id: "e16", q: "The synonym of 'MITIGATE' is:", a: ["Increase", "Alleviate/Lessen", "Aggravate", "Destroy"], c: 1 },
        { id: "e17", q: "Hardly had I arrived at the station _______ the train left.", a: ["than", "then", "when", "that"], c: 2 },
        { id: "e18", q: "Choose the antonym of 'OBSOLETE':", a: ["Ancient", "Outdated", "Modern", "Fragile"], c: 2 },
        { id: "e19", q: "The idiom 'Burn the midnight oil' means:", a: ["To waste fuel", "To study or work late into the night", "To create a fire hazard", "To wake up early"], c: 1 },
        { id: "e20", q: "He behaves as if he ________ a king.", a: ["is", "was", "were", "has been"], c: 2 }
    ]
};
